name: disp-s1-env
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - click>=7.0
  - dolphin>=0.22.0
  - h5netcdf>=1.0
  - pillow>=7.0
  - pydantic>=2.1
  - ruamel.yaml>=0.15
  - yamale
  # Corrections
  - pysolid  # For solid earth tide corrections
  - pyaps3
  # Unwrappers:
  - snaphu>=0.4.0
  - isce3>=0.16.0
  - tophu
  # # Spurt is not yet on pip/conda, but only has one extra (...which also is badly supported on conda-forge)
  # - ortools==9.8.3296
  # - pip
  #   - dolphin>=0.23.0
  #   - git+https://github.com/isce-framework/spurt@21720e6ad6763d38c428c07331c8cfd395cdacd3
